package es.idynamicsax.ostris.service;

import static org.junit.jupiter.api.Assertions.*;
import es.idynamicsax.ostris.config.OstrisFlywayConfig;
import es.idynamicsax.ostris.core.ProtocolException;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.*;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.WebApplicationType;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@Testcontainers(disabledWithoutDocker=true) @TestInstance(TestInstance.Lifecycle.PER_CLASS)
class IdentityContinuityPostgresTest {
 @Container static final PostgreSQLContainer<?> POSTGRES=new PostgreSQLContainer<>("postgres:17").withDatabaseName("ostris").withUsername("postgres").withPassword("test").withInitScript("postgres-init.sql");
 ConfigurableApplicationContext context;IdentityContinuityService service;JdbcTemplate jdbc;
 static final UUID TENANT=UUID.fromString("00000000-0000-0000-0000-00000000000a"),OTHER_TENANT=UUID.fromString("00000000-0000-0000-0000-00000000000b"),COMMUNITY=UUID.fromString("018f6f9a-7b1c-7a2b-8c3d-4e5f60719001"),OTHER_COMMUNITY=UUID.fromString("018f6f9a-7b1c-7a2b-8c3d-4e5f60719002"),RISK=UUID.fromString("018f6f9a-7b1c-7a2b-8c3d-4e5f60719003"),A=UUID.fromString("018f6f9a-7b1c-7a2b-8c3d-4e5f60719004"),B=UUID.fromString("018f6f9a-7b1c-7a2b-8c3d-4e5f60719005"),C=UUID.fromString("018f6f9a-7b1c-7a2b-8c3d-4e5f60719006"),CLAIM=UUID.fromString("018f6f9a-7b1c-7a2b-8c3d-4e5f60719007");
 @BeforeAll void start(){restart();jdbc.update("insert into idax_core.tenant values(?),(?)",TENANT,OTHER_TENANT);jdbc.update("insert into ostris.community(id,tenant_id,name) values(?,?,?),(?,?,?)",COMMUNITY,TENANT,"A",OTHER_COMMUNITY,TENANT,"B");jdbc.update("insert into ostris.risk_subject(id,tenant_id,community_id) values(?,?,?)",RISK,TENANT,COMMUNITY);jdbc.update("insert into ostris.participant(id,tenant_id,community_id,risk_subject_id,display_name) values(?,?,?,?,?),(?,?,?,?,?),(?,?,?,?,?)",A,TENANT,COMMUNITY,RISK,"Profile A",B,TENANT,COMMUNITY,null,"Profile B",C,TENANT,COMMUNITY,null,"Profile C");jdbc.update("insert into ostris.identity_assurance_claim(id,tenant_id,community_id,risk_subject_id,provider_id,opaque_subject_ref,claim_profile,issued_at,status,revocation_sequence) values(?,?,?,?,?,?,?,now(),'REVOKED',1)",CLAIM,TENANT,COMMUNITY,RISK,"provider","opaque","basic");}
 @AfterAll void stop(){if(context!=null)context.close();}
 void restart(){context=new SpringApplicationBuilder(TestApp.class).web(WebApplicationType.NONE).run("--spring.datasource.url="+POSTGRES.getJdbcUrl(),"--spring.datasource.username="+POSTGRES.getUsername(),"--spring.datasource.password="+POSTGRES.getPassword(),"--spring.jpa.hibernate.ddl-auto=none","--spring.flyway.enabled=false");service=context.getBean(IdentityContinuityService.class);jdbc=context.getBean(JdbcTemplate.class);}
 @Test void confirmedSocialResetKeepsPrivateRiskSubjectAcrossRestart(){UUID decision=UUID.fromString("018f6f9a-7b1c-7a2b-8c3d-4e5f60719101");var result=service.decide(TENANT,new IdentityContinuityService.DecisionCommand(decision,COMMUNITY,B,RISK,IdentityContinuityService.Status.CONFIRMED,List.of("opaque-evidence"),"community-review","confirmed",null));assertEquals(RISK,result.riskSubjectId());assertEquals(RISK,jdbc.queryForObject("select risk_subject_id from ostris.participant where id=?",UUID.class,A));assertEquals(RISK,jdbc.queryForObject("select risk_subject_id from ostris.participant where id=?",UUID.class,B));var publicView=service.publicParticipant(TENANT,COMMUNITY,B);assertEquals("Profile B",publicView.displayName());assertFalse(publicView.toString().contains(RISK.toString()));context.close();context=null;restart();assertEquals(RISK,service.resolvePrivate(TENANT,COMMUNITY,B).riskSubjectId());}
 @Test void contestedProducesReviewWithoutEconomicOrRiskLink(){UUID decision=UUID.fromString("018f6f9a-7b1c-7a2b-8c3d-4e5f60719102");var result=service.decide(TENANT,new IdentityContinuityService.DecisionCommand(decision,COMMUNITY,C,RISK,IdentityContinuityService.Status.CONTESTED,List.of(),"community-review","contested",null));assertEquals("REQUIRE_REVIEW",result.outcome());assertNull(result.riskSubjectId());assertNull(jdbc.queryForObject("select risk_subject_id from ostris.participant where id=?",UUID.class,C));assertEquals(0,jdbc.queryForObject("select count(*) from ostris.journal_transaction",Integer.class));}
 @Test void continuityScopeAssuranceAndUuidMatrixFailsClosed(){UUID d=UUID.fromString("018f6f9a-7b1c-7a2b-8c3d-4e5f60719103");assertEquals("PARTICIPANT_NOT_IN_SCOPE",assertThrows(ProtocolException.class,()->service.decide(TENANT,new IdentityContinuityService.DecisionCommand(d,OTHER_COMMUNITY,B,RISK,IdentityContinuityService.Status.CONFIRMED,List.of(),"review","x",null))).code());assertEquals("PARTICIPANT_NOT_IN_SCOPE",assertThrows(ProtocolException.class,()->service.decide(OTHER_TENANT,new IdentityContinuityService.DecisionCommand(d,COMMUNITY,B,RISK,IdentityContinuityService.Status.CONFIRMED,List.of(),"review","x",null))).code());assertEquals("PARTICIPANT_NOT_IN_SCOPE",assertThrows(ProtocolException.class,()->service.decide(TENANT,new IdentityContinuityService.DecisionCommand(d,COMMUNITY,UUID.fromString("018f6f9a-7b1c-7a2b-8c3d-4e5f60719991"),RISK,IdentityContinuityService.Status.CONFIRMED,List.of(),"review","x",null))).code());assertEquals("RISK_SUBJECT_NOT_IN_SCOPE",assertThrows(ProtocolException.class,()->service.decide(TENANT,new IdentityContinuityService.DecisionCommand(d,COMMUNITY,B,UUID.fromString("018f6f9a-7b1c-7a2b-8c3d-4e5f60719992"),IdentityContinuityService.Status.CONFIRMED,List.of(),"review","x",null))).code());assertEquals("ASSURANCE_NOT_EFFECTIVE",assertThrows(ProtocolException.class,()->service.decide(TENANT,new IdentityContinuityService.DecisionCommand(d,COMMUNITY,B,RISK,IdentityContinuityService.Status.CONFIRMED,List.of(),"review","x",CLAIM))).code());assertEquals("INVALID_UUID_V7",assertThrows(ProtocolException.class,()->service.decide(TENANT,new IdentityContinuityService.DecisionCommand(UUID.randomUUID(),COMMUNITY,B,RISK,IdentityContinuityService.Status.CONFIRMED,List.of(),"review","x",null))).code());}
 @Test void latestEffectiveSequenceWinsAndFutureDecisionDoesNot(){UUID rejected=UUID.fromString("018f6f9a-7b1c-7a2b-8c3d-4e5f60719104");service.decide(TENANT,new IdentityContinuityService.DecisionCommand(rejected,COMMUNITY,B,RISK,IdentityContinuityService.Status.REJECTED,List.of(),"appeal","rejected",null));assertEquals(IdentityContinuityService.Status.REJECTED,service.resolvePrivate(TENANT,COMMUNITY,B).status());assertNull(service.resolvePrivate(TENANT,COMMUNITY,B).riskSubjectId());UUID future=UUID.fromString("018f6f9a-7b1c-7a2b-8c3d-4e5f60719105");jdbc.update("insert into ostris.identity_continuity_decision(id,tenant_id,community_id,risk_subject_id,participant_id,status,decision_authority,community_sequence) values(?,?,?,?,?,'CONFIRMED','future',9999)",future,TENANT,COMMUNITY,RISK,B);assertEquals(IdentityContinuityService.Status.REJECTED,service.resolvePrivate(TENANT,COMMUNITY,B).status());}
 @SpringBootConfiguration @EnableAutoConfiguration @Import({OstrisFlywayConfig.class,IdentityContinuityService.class}) static class TestApp{}
}
