package es.idynamicsax.ostris.api;
import es.idynamicsax.idax.tenant.TenantContext; import es.idynamicsax.ostris.core.TransactionPurpose; import es.idynamicsax.ostris.service.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.util.*; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/ostris/transactions") public class TransactionController {
 private final ProposalAuthorizationService service; public TransactionController(ProposalAuthorizationService s){service=s;}
 @PostMapping("/proposals") @PreAuthorize("@permissionService.hasPermission('OSTRIS_TRANSACTION_CREATE')") ResponseEntity<ProposalAuthorizationService.ProposalView> propose(@Valid @RequestBody Request r){UUID tenant=TenantContext.get().getTenantId();var entries=r.entries().stream().map(e->new CommitTransactionCommand.Entry(e.accountId(),e.amount())).toList();return ResponseEntity.status(HttpStatus.CREATED).body(service.propose(new CommitTransactionCommand(tenant,r.communityId(),r.unitId(),r.transactionId(),r.purpose(),entries,r.references(),r.contractualMetadataDigest(),r.resolutionBasisType(),r.resolutionBasisId())));}
 @PostMapping("/{id}/authorizations") @PreAuthorize("@permissionService.hasPermission('OSTRIS_TRANSACTION_AUTHORIZE')") ResponseEntity<Void> authorize(@PathVariable UUID id,@Valid @RequestBody AccountAuthorization r){service.addAccountEvidence(TenantContext.get().getTenantId(),id,r.accountId(),r.credentialId(),r.signatureBase64url());return ResponseEntity.noContent().build();}
 @PostMapping("/{id}/governance-authorizations") @PreAuthorize("@permissionService.hasPermission('OSTRIS_TRANSACTION_AUTHORIZE')") ResponseEntity<Void> govern(@PathVariable UUID id,@Valid @RequestBody GovernanceAuthorization r){service.addGovernanceEvidence(TenantContext.get().getTenantId(),id,r.authorityId(),r.authorityPolicyVersion(),r.resolutionBasisType(),r.resolutionBasisId(),r.coveredAccounts(),r.credentialId(),r.signatureBase64url());return ResponseEntity.noContent().build();}
 @PostMapping("/{id}/commit") @PreAuthorize("@permissionService.hasPermission('OSTRIS_TRANSACTION_COMMIT')") ResponseEntity<CommitReceipt> commit(@PathVariable UUID id){return ResponseEntity.ok(service.commit(TenantContext.get().getTenantId(),id));}
 public record Request(@NotNull UUID communityId,@NotNull UUID unitId,@NotNull UUID transactionId,@NotNull TransactionPurpose purpose,@NotEmpty List<@Valid Entry> entries,Map<String,String> references,String contractualMetadataDigest,es.idynamicsax.ostris.core.ResolutionBasisType resolutionBasisType,UUID resolutionBasisId){}
 public record Entry(@NotNull UUID accountId,@NotBlank String amount){}
 public record AccountAuthorization(@NotNull UUID accountId,@NotNull UUID credentialId,@NotBlank String signatureBase64url){}
 public record GovernanceAuthorization(@NotNull UUID authorityId,@Positive int authorityPolicyVersion,@NotNull es.idynamicsax.ostris.core.ResolutionBasisType resolutionBasisType,@NotNull UUID resolutionBasisId,@NotEmpty Set<UUID> coveredAccounts,@NotNull UUID credentialId,@NotBlank String signatureBase64url){}
}
